'use client'

import { DOC_LABELS, slug } from '@/lib/utils'

function Field({label,name,form,setForm,type='text',options,textarea=false}:{label:string,name:string,form:any,setForm:any,type?:string,options?:[string,string][],textarea?:boolean}){
  return <label className="field"><span>{label}</span>{options?<select value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:textarea?<textarea rows={3} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input type={type} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</label>
}

export default function Modal({kind,form,setForm,close,saveBrand,saveTerms,savePromo,saveRep,uploadDocument,brands,supabase,session,reload}:any){
  async function saveProduct(){
    const name=form.name?.trim(); if(!name)return
    let candidate=slug(name),n=2
    while((await supabase.from('products').select('id',{count:'exact',head:true}).eq('slug',candidate)).count)candidate=`${slug(name)}-${n++}`
    const {error}=await supabase.from('products').insert({name,slug:candidate,brand_id:form.brand_id||null,status:'draft',manufacturer_code:form.manufacturer_code||null,product_type:form.product_type||null,created_by:session.user.id,updated_by:session.user.id})
    if(error)alert(error.message);else{close();reload()}
  }
  const title=kind==='brand'?'Fornecedor / Marca':kind==='upload'?'Importar arquivo':kind==='terms'?'Nova condição comercial':kind==='promo'?'Nova promoção':kind==='rep'?'Novo representante':'Novo produto'
  const submit=()=>kind==='brand'?saveBrand():kind==='terms'?saveTerms():kind==='promo'?savePromo():kind==='rep'?saveRep():kind==='product'?saveProduct():(document.getElementById('uploadForm') as HTMLFormElement|null)?.requestSubmit()
  return <div className="modalBg" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal">
    <div className="modalHead"><div><span className="eyebrow">SB PRODUCT BRAIN</span><h2>{title}</h2></div><button onClick={close}>×</button></div>
    {kind==='brand'&&<div className="formGrid"><Field label="Nome" name="name" form={form} setForm={setForm}/><Field label="Código interno" name="internal_code" form={form} setForm={setForm}/><Field label="Razão social" name="legal_name" form={form} setForm={setForm}/><Field label="CNPJ" name="tax_id" form={form} setForm={setForm}/><Field label="Site" name="website_url" form={form} setForm={setForm}/><Field label="E-mail" name="email" form={form} setForm={setForm}/><Field label="Telefone" name="phone" form={form} setForm={setForm}/><Field label="Cidade" name="city" form={form} setForm={setForm}/><Field label="UF" name="state" form={form} setForm={setForm}/><Field label="Observações" name="notes" form={form} setForm={setForm} textarea/></div>}
    {kind==='product'&&<div className="formGrid"><Field label="Nome" name="name" form={form} setForm={setForm}/><Field label="Código do fornecedor" name="manufacturer_code" form={form} setForm={setForm}/><Field label="Tipo" name="product_type" form={form} setForm={setForm}/><label className="field"><span>Fornecedor / Marca</span><select value={form.brand_id||''} onChange={e=>setForm({...form,brand_id:e.target.value})}><option value="">Sem fornecedor</option>{brands.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div>}
    {kind==='terms'&&<div className="formGrid"><Field label="Válida desde" name="valid_from" type="date" form={form} setForm={setForm}/><Field label="Até" name="valid_until" type="date" form={form} setForm={setForm}/><Field label="Markup alvo" name="target_markup" type="number" form={form} setForm={setForm}/><Field label="Markup mínimo" name="minimum_markup" type="number" form={form} setForm={setForm}/><Field label="Prazo mín. dias" name="lead_time_min_days" type="number" form={form} setForm={setForm}/><Field label="Prazo máx. dias" name="lead_time_max_days" type="number" form={form} setForm={setForm}/><Field label="Pagamento" name="payment_terms" form={form} setForm={setForm}/><Field label="IPI" name="ipi_mode" form={form} setForm={setForm} options={[["unknown","A definir"],["included","Incluso"],["additional_percent","Adicionar %"],["not_applicable","Não incide"]]}/><Field label="IPI %" name="ipi_rate" type="number" form={form} setForm={setForm}/><Field label="Frete" name="freight_mode" form={form} setForm={setForm} options={[["unknown","A definir"],["included","Incluso"],["additional_percent","Adicionar %"],["additional_fixed","Adicionar valor"],["fob","FOB / posterior"],["not_applicable","Não incide"]]}/><Field label="Frete valor / %" name="freight_value" type="number" form={form} setForm={setForm}/><Field label="Observações" name="notes" form={form} setForm={setForm} textarea/></div>}
    {kind==='promo'&&<div className="formGrid"><Field label="Nome" name="name" form={form} setForm={setForm}/><Field label="Desconto %" name="discount_percent" type="number" form={form} setForm={setForm}/><Field label="Início" name="valid_from" type="date" form={form} setForm={setForm}/><Field label="Fim" name="valid_until" type="date" form={form} setForm={setForm}/><Field label="Descrição" name="description" form={form} setForm={setForm} textarea/><Field label="Regras / escopo" name="rules_notes" form={form} setForm={setForm} textarea/></div>}
    {kind==='rep'&&<div className="formGrid"><Field label="Nome" name="contact_name" form={form} setForm={setForm}/><Field label="Empresa representante" name="company_name" form={form} setForm={setForm}/><Field label="E-mail" name="email" form={form} setForm={setForm}/><Field label="Telefone" name="phone" form={form} setForm={setForm}/><Field label="WhatsApp" name="whatsapp" form={form} setForm={setForm}/><Field label="Região" name="region" form={form} setForm={setForm}/><label className="check"><input type="checkbox" checked={!!form.is_primary} onChange={e=>setForm({...form,is_primary:e.target.checked})}/> Representante principal</label><Field label="Notas" name="notes" form={form} setForm={setForm} textarea/></div>}
    {kind==='upload'&&<form id="uploadForm" onSubmit={uploadDocument}><div className="formGrid"><label className="field span2"><span>Arquivo</span><input name="file" type="file" accept=".xlsx,.xls,.csv,.pdf" required/></label><Field label="Tipo de documento" name="document_type" form={form} setForm={setForm} options={Object.entries(DOC_LABELS) as [string,string][]}/><Field label="Tabela é de" name="price_basis" form={form} setForm={setForm} options={[["cost","Custo"],["sale","Venda"],["na","Não se aplica"]]}/><Field label="IPI" name="ipi_mode" form={form} setForm={setForm} options={[["unknown","A definir"],["included","Já incluso"],["additional_percent","Adicionar %"],["not_applicable","Não incide"]]}/><Field label="IPI %" name="ipi_rate" type="number" form={form} setForm={setForm}/><Field label="Frete" name="freight_mode" form={form} setForm={setForm} options={[["unknown","A definir"],["included","Incluso"],["additional_percent","Adicionar %"],["additional_fixed","Adicionar valor"],["fob","FOB / calcular depois"],["not_applicable","Não incide"]]}/><Field label="Frete % / valor" name="freight_value" type="number" form={form} setForm={setForm}/><Field label="Vigência inicial" name="valid_from" type="date" form={form} setForm={setForm}/><Field label="Vigência final" name="valid_until" type="date" form={form} setForm={setForm}/><Field label="Instruções para Astra" name="processing_instructions" form={form} setForm={setForm} textarea/></div></form>}
    <div className="modalActions"><button onClick={close}>Cancelar</button><button className="primary" onClick={submit}>{kind==='upload'?'Enviar e interpretar':'Salvar'}</button></div>
  </div></div>
}
